lint

diff --git a/.github/workflows/build_lint.yaml b/.github/workflows/build_lint.yaml
--- a/.github/workflows/build_lint.yaml
+++ b/.github/workflows/build_lint.yaml
@@ -10,6 +10,26 @@ on:
       - main
 
 jobs:
+  linter:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: cpp-linter/cpp-linter-action@main
+        id: linter
+        continue-on-error: true
+        # env:
+        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          style: file
+          files-changed-only: false
+          thread-comments: false
+
+      - name: Fail fast?!
+        if: steps.linter.outputs.checks-failed != 0
+        run: |
+          echo "some linter checks failed. ${{ steps.linter.outputs.checks-failed }}"
+          exit 1
+
   build:
     runs-on: ubuntu-latest
 
